---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Parisi Home"
subtitle: "Home Services"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Homeassistant"
        logo: "assets/tools/sample.png"
        subtitle: ""
        tag: "app"
        keywords: "homeassistant"
        url: "http://homeassistant.local:8123/"
        target: "_blank"
      - name: "qBittorrent"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        keywords: "torrent"
        url: "http://192.168.5.141:8090/"
        target: "_blank"
      - name: "NAS Dashboard"
        logo: "assets/tools/sample.png"
        subtitle: "Netgear NAS"
        tag: "app"
        keywords: "torrent"
        url: "http://nas.local"
        target: "_blank"
      - name: "ESPHome"
        logo: "assets/tools/sample.png"
        subtitle: "ESPHome management"
        tag: "app"
        url: "http://192.168.5.18:6052/"
        target: "_blank"
      - name: "Sofar2MQTT"
        logo: "assets/tools/sample.png"
        subtitle: "Sofar2MQTT"
        tag: "app"
        url: "http://192.168.5.45/"
        target: "_blank"
      - name: "Zigbee2MQTT"
        logo: "assets/tools/sample.png"
        subtitle: "Zigbee2MQTT"
        tag: "app"
        url: "http://homeassistant.local:8123/hassio/ingress/45df7312_zigbee2mqtt"
        target: "_blank"
      - name: "SLZB-06"
        logo: "assets/tools/sample.png"
        subtitle: "Zigbee Coordinator"
        tag: "app"
        url: "http://192.168.5.31/"
        target: "_blank"
  - name: "Server"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox VE"
        logo: "assets/tools/sample.png"
        subtitle: ""
        tag: "app"
        url: "https://192.168.5.3:8006/"
        target: "_blank"
      - name: "NGINX Proxy Manager"
        logo: "assets/tools/sample.png"
        subtitle: "Proxy Manager"
        tag: "app"
        url: "http://192.168.5.54:81/"
        target: "_blank"
  - name: "Management"
    icon: "fas fa-cloud"
    items:
      - name: "Mikrotik Router"
        logo: "assets/tools/sample.png"
        subtitle: "Router dashboard"
        tag: "app"
        url: "http://192.168.5.1/"
        target: "_blank"
      - name: "Mikrotik AP"
        logo: "assets/tools/sample.png"
        subtitle: "Attic AP dashboard"
        tag: "app"
        url: "http://192.168.5.48/"
        target: "_blank"
      - name: "UniFi Dashboard"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "unifi network"
        url: "https://network.unifi.ui.com/8.0.26.0/unifi/site/default/dashboard/?d=0fa2ad5a-23c9-4e32-9376-472d81ab038f"
        target: "_blank" # optional html a tag target attribute
      - name: "Linksys PAP"
        logo: "assets/tools/sample.png"
        subtitle: "Phone adapter"
        tag: "app"
        url: "http://192.168.5.24/"
        target: "_blank"
