version: "3.8"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    ports:
      - "8080:8080"              # map as you like
    volumes:
      - ./config:/www/assets     # your config folder in git
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Dublin
